# Generated by Django 3.1.1 on 2022-06-04 22:26

from django.db import migrations, models
import paginas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('marcaProducto', models.CharField(blank=True, max_length=30, null=True)),
                ('nombreProducto', models.CharField(blank=True, max_length=30, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
