# Generated by Django 3.1.1 on 2022-06-05 02:56

from django.db import migrations, models
import paginas.models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('idPersona', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombrePersona', models.CharField(blank=True, max_length=30, null=True)),
                ('usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(null=True, upload_to=paginas.models.cargarFotoPersona)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
