# Generated by Django 3.1.1 on 2022-06-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_auto_20220604_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='telefono',
        ),
    ]
