# Generated by Django 3.1.1 on 2022-06-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_remove_personas_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='tipoUsuario',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
