# Generated by Django 3.1.1 on 2022-06-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_personas_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='tipoUsuario',
        ),
    ]
