# Generated by Django 3.1.1 on 2022-06-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_remove_personas_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='tipoUsuario',
            field=models.CharField(blank=True, choices=[('Usuario', 'Usuario')], max_length=30),
        ),
    ]
