# Generated by Django 3.1.1 on 2022-06-23 18:56

from django.db import migrations, models
import paginas.models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_auto_20220623_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='foto',
            field=models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto),
        ),
        migrations.AlterField(
            model_name='venta',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
