# Generated by Django 3.1.1 on 2022-06-24 01:18

from django.db import migrations, models
import paginas.models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0018_auto_20220623_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='foto',
            field=models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.IntegerField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
