# Generated by Django 3.1.1 on 2022-06-24 01:22

from django.db import migrations, models
import paginas.models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0020_auto_20220623_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='producto_id',
            new_name='idProducto',
        ),
        migrations.AlterField(
            model_name='personas',
            name='foto',
            field=models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto),
        ),
    ]
