# Generated by Django 3.1.1 on 2022-06-24 03:19

from django.db import migrations, models
import paginas.models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0021_auto_20220623_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='idProducto',
        ),
        migrations.AlterField(
            model_name='personas',
            name='foto',
            field=models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto),
        ),
    ]
