# Generated by Django 3.1.1 on 2022-06-24 22:50

from django.db import migrations, models
import django.db.models.deletion
import paginas.models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0022_auto_20220623_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='producto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paginas.producto'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='foto',
            field=models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto),
        ),
    ]
