# Generated by Django 3.1.1 on 2022-06-24 22:57

from django.db import migrations, models
import paginas.models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0023_auto_20220624_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.AlterField(
            model_name='personas',
            name='foto',
            field=models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to=paginas.models.cargarFotoProducto),
        ),
    ]
